# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photo')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
