# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 02:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0008_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(related_name='liked_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
