# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_post_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked2',
            new_name='liked',
        ),
    ]
