# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20171018_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='subscriber',
        ),
    ]
