# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_remove_subscribe_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='post.Subscribe')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='post.Subscribe')),
            ],
        ),
        migrations.AddField(
            model_name='subscribe',
            name='subscriber',
            field=models.ManyToManyField(through='post.SubRelation', to='post.Subscribe'),
        ),
    ]
