# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20171018_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subrelation',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='subrelation',
            name='following',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='subscriber',
        ),
        migrations.DeleteModel(
            name='SubRelation',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
