# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_auto_20171019_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subrelation',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='subrelation',
            name='following',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='user',
        ),
        migrations.DeleteModel(
            name='SubRelation',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
