# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_auto_20171019_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrelation',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
