# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_auto_20171019_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='subscriber',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
